nmap <leader>tb= :Tabularize /=<CR>
vmap <leader>tb= :Tabularize /=<CR>
nmap <leader>tb: :Tabularize /:<CR>
vmap <leader>tb: :Tabularize /:<CR>
nmap <leader>tb:: :Tabularize /:\zs<CR>
vmap <leader>tb:: :Tabularize /:\zs<CR>
nmap <leader>tb, :Tabularize /,<CR>
vmap <leader>tb, :Tabularize /,<CR>
nmap <leader>tb<Bar> :Tabularize /<Bar><CR>
vmap <leader>tb<Bar> :Tabularize /<Bar><CR>
nmap <leader>tb( :Tabularize /(/l1l0<CR>
vmap <leader>tb( :Tabularize /(/l1l0<CR>
